### ISSUE TITLE
Negative RegEx not working

### ISSUE THREAD

**Issue by Root-Core** [webpack-contrib/zopfli-webpack-plugin#10]
Hello there,

at the moment you can not exclude files from being processed.
As I do compress with brotli in addition to gzip, this lead to processing of Brotli files with Zopfli.

The `compression-webpack-plugin` allows me to use negative regex.
Zopfli does not.

```javascript
    // Generate static compressed assets ('minRatio: 2' ensures output)
    new BrotliPlugin({ minRatio: 2 }), // Do not gzip brotli files
    new ZopfliPlugin({ minRatio: 2, test: /^.*\.(?!br)[^.]+$/ })
```

Regards.

**Comment by alexander-akait** [comment]
This package deprecated in favor https://github.com/webpack-contrib/compression-webpack-plugin, please look how use `zopfli` library https://github.com/webpack-contrib/compression-webpack-plugin#examples. You can use `node-zopfli` instead `@gfx/zopfli` if you need `node@6` support. Thanks for using webpack.
