### ISSUE TITLE
Update package.json for Webpack 4

### ISSUE THREAD

**Issue by mnpenner** [webpack-contrib/zopfli-webpack-plugin#11]
This plugin seems to work fine under Webpack 4.

Could you just update [this line](https://github.com/webpack-contrib/zopfli-webpack-plugin/blob/45e7adbca7d45cf0c915b3fdbf108dcb72385bf1/package.json#L58) to fix the peer dependency warning given by yarn/npm?

> warning " > zopfli-webpack-plugin@0.1.0" has incorrect peer dependency "webpack@^2.0.0 || ^3.0.0".

**Comment by alexander-akait** [comment]
@mnpenner Thanks for issue, will do in near future :+1:

**Comment by tomasaschan** [comment]
@evilebottnawi Any progress on this? :)

**Comment by alexander-akait** [comment]
Sorry, don't have time right now for this :disappointed: PR welcome :+1:

**Comment by alexander-akait** [comment]
This package deprecated in favor https://github.com/webpack-contrib/compression-webpack-plugin, please look how use `zopfli` library https://github.com/webpack-contrib/compression-webpack-plugin#examples. You can use `node-zopfli` instead `@gfx/zopfli` if you need `node@6` support. Thanks for using webpack.
