### ISSUE TITLE
node-zopfli support

### ISSUE THREAD

**Issue by sshmyg** [webpack-contrib/zopfli-webpack-plugin#13]
node-zopfli doesn't support anymore.

wind 10 has a problem with this package. And as a result this webpack plugin doesn't work any more for windows 10.

https://github.com/pierreinglebert/node-zopfli/issues/85

**Comment by alexander-akait** [comment]
@sshmyg very strange, let's wait development answer, feel free ti ping me

**Comment by sshmyg** [comment]
@evilebottnawi Issue about w10 bug was create at `Feb 21, 2017` so I can suggest we will not get any answer in nearest time.

**Comment by alexander-akait** [comment]
@sshmyg ideas?

**Comment by alexander-akait** [comment]
This package deprecated in favor https://github.com/webpack-contrib/compression-webpack-plugin, please look how use `zopfli` library https://github.com/webpack-contrib/compression-webpack-plugin#examples. You can use `node-zopfli` instead `@gfx/zopfli` if you need `node@6` support. Thanks for using webpack.
