### ISSUE TITLE
Couldn't find package "zopfli-webpack-plugin" on the "npm" registry

### ISSUE THREAD

**Issue by koalex** [webpack-contrib/zopfli-webpack-plugin#3]
`npm i -D zopfli-webpack-plugin` throws an error

**Comment by joshwiens** [comment]
@koalex - Currently, the `zopfli` option still exists in https://github.com/webpack-contrib/compression-webpack-plugin 

To this lib specifically, I need to author the test suite for the split out plugin and decide if i'm going to modify the api before I publish a beta version.

I should have an initial version out this weekend.

**Comment by koalex** [comment]
Thanks.
Please close this issue when the repository will be on npm.

**Comment by thasmo** [comment]
Any updates on this? :) Thanks! :+1:

**Comment by joshwiens** [comment]
Initial version published as `zopfli-webpack-plugin@0.1.0`
