### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by fedorovvldmr** [webpack-contrib/zopfli-webpack-plugin#4]
> node-pre-gyp ERR! Tried to download(403): https://node-zopfli.s3.amazonaws.com/Release/zopfli-v2.0.2-node-v57-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for node-zopfli@2.0.2 and node@8.4.0 (node-v57 ABI) (falling back to source compile with node-gyp)

**Comment by alexander-akait** [comment]
@fedorovvldmr seems you don't have access to  https://node-zopfli.s3.amazonaws.com/Release/zopfli-v2.0.2-node-v57-win32-x64.tar.gz (403 error)

**Comment by fedorovvldmr** [comment]
npm 5.3.0
nodejs v8.4.0
Tested on PC Lenovo Z500 Windows 8.1 and VPS server Debian 7 x64. On both same error 403. Other packages are installed without problems.
Sorry for bad english

**Comment by alexander-akait** [comment]
@fedorovvldmr i have message:
```
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>42C145916E16AE4F</RequestId>
<HostId>
8XYeUzRXhqrOJy63EZ+aYX0d3P+po7gMn3s5PVo37yytGk9uJzAf7lK15hiGq4j99EEKQaRM5T8=
</HostId>
</Error>
```
You don't have access to download this

**Comment by fedorovvldmr** [comment]
I get the same result
```
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>D94042D5FFD13DD9</RequestId>
<HostId>+RCwmJqhy0YAHtpuYMCQqAVCcVHKuMxIU0KycI1i4UNHDDxarI2AiTI4jS99WBsn9nlxhBNXhoc=</HostId>
</Error>
```

**Comment by colshacol** [comment]
Same here.
![screen shot 2017-11-02 at 11 46 26 am](https://user-images.githubusercontent.com/19484365/32338690-7e860bce-bfc3-11e7-8982-ead88acbd193.png)

**Comment by JoeKahl** [comment]
Similar issue for me:

```
C:\Users\user\Source\Repos\clientservicemgmt-fe>npm i -D zopfli-webpack-plugin

> node-zopfli@2.0.2 install C:\Users\jkahl1\Source\Repos\clientservicemgmt-fe\node_modules\node-zopfli
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(undefined): https://node-zopfli.s3.amazonaws.com/Release/zopfli-v2.0.2-node-v48-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for node-zopfli@2.0.2 and node@6.11.1 (node-v48 ABI, unknown) (falling back to source compile with node-gyp)

```
What is going on here?  Must I roll back my node version?
What does amazonaws.com have to do with this package?

**Comment by ingria** [comment]
I've had the same issue. After some investigation it turned out that the problem is in node-gyp. It is trying to either download the binaries from `amazonaws.com`, or build them from sources.

`*.s3.amazonaws.com` doesn't work for some ****** reason, so the solution is to give the `node-gyp` ability to build binary from source. On Linux it can be done with this command:

```
sudo apt install build-essential
```

**Comment by alexander-akait** [comment]
@ingria after install `build-essential` all work fine?

**Comment by ingria** [comment]
Yes, but `build-essential` is available only on Linux. 

Anyway, this issue is not related with `zopfli-webpack-plugin`, there's nothing you can do.

**Comment by alexander-akait** [comment]
@ingria thanks for information :+1:

**Comment by corydeppen** [comment]
Is there a solution for folks "lucky" enough to be using Windows?
