### ISSUE TITLE
CopyWebpackPlugin assets are not getting minified

### ISSUE THREAD

**Issue by eseliger** [webpack-contrib/zopfli-webpack-plugin#7]
I believe this is due to the event listened on. It should rather be `emit` and not `this-compilation`, which makes sense, I  believe. Compressing should always be the last step and not happen between two output modifications as the minified content is outdated then (or, as in this case, not catched).

**Comment by alexander-akait** [comment]
@eseliger seems you are right, we use other event in https://github.com/webpack-contrib/compression-webpack-plugin/blob/master/src/index.js#L67, PR welcome :+1:
